"""
LLMDelegate: Abstraction layer for LLM-based form field decisions.

Based on creative phase design document.
"""

import logging
from abc import ABC, abstractmethod
from typing import Optional, Dict, Any, Literal

from pydantic import BaseModel, Field, field_validator, model_validator

from modal_flow.profile_schema import CandidateProfile


class SuggestedStrategy(BaseModel):
    """Suggested strategy structure for new rules."""
    kind: str
    params: Optional[Dict[str, Any]] = None


class LLMDecision(BaseModel):
    """
    Structured response from LLM for field decision.
    
    Based on technical specification section 4.4.
    """
    decision: Literal["select", "text", "number", "check", "skip"]
    value: Any
    confidence: float = Field(..., ge=0, le=1)
    suggest_rule: Optional[Dict[str, Any]] = None
    # NOTE: suggest_rule is deprecated. Rule generation is now handled separately
    # via generate_rule() method. This field is kept for backward compatibility.
    
    class Config:
        # Allow extra fields for flexibility
        extra = "allow"


class StrategyDefinition(BaseModel):
    """
    Strategy definition for rule execution.
    
    Represents how a field should be filled based on the rule.
    """
    kind: str = Field(..., description="Strategy kind: literal, profile_key, numeric_from_profile, one_of_options, one_of_options_from_profile, salary_by_currency")
    params: Dict[str, Any] = Field(default_factory=dict, description="Strategy-specific parameters")
    
    @model_validator(mode='after')
    def validate_params(self):
        """Validate that params contain required fields for each strategy kind."""
        kind = self.kind
        params = self.params or {}
        
        # Keep strict validation only for 'literal' to avoid early hard failures.
        if kind == "literal":
            if "value" not in params:
                raise ValueError(f"Strategy 'literal' requires 'value' in params, got: {params}")
        
        # For other strategies (profile_key, numeric_from_profile, one_of_options,
        # one_of_options_from_profile, salary_by_currency) do not raise here.
        # They will be validated or fixed later during rule processing.
        return self


class RuleSuggestion(BaseModel):
    """
    Structured response for rule generation.
    
    Represents a rule suggestion generated by LLM for automatic form field filling.
    """
    q_pattern: str = Field(..., description="Regex pattern to match the field question")
    strategy: StrategyDefinition = Field(..., description="Strategy definition with kind and params")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence score for this rule")


class BaseLLMDelegate(ABC):
    """
    Abstract base class for LLM delegates.
    
    Provides a common interface for different LLM providers.
    """
    
    @abstractmethod
    async def decide(
        self,
        field_info: Dict[str, Any],
        profile: CandidateProfile,
        job_context: Optional[Dict[str, Any]] = None
    ) -> LLMDecision:
        """
        Ask the LLM to make a decision for a given field.
        
        Args:
            field_info: Dictionary containing field information:
                - question: str
                - field_type: str (radio, checkbox, select, text, number)
                - options: Optional[List[str]]
                - required: bool
            profile: Candidate profile
            job_context: Optional job context (job title, description, etc.)
            
        Returns:
            LLMDecision with decision, value, confidence, and optional suggest_rule
        """
        pass
    
    @abstractmethod
    async def generate_rule(
        self,
        field_info: Dict[str, Any],
        selected_value: Any,
        profile: CandidateProfile,
        job_context: Optional[Dict[str, Any]] = None
    ) -> Optional["RuleSuggestion"]:
        """
        Generate a rule for a field based on the decision made.
        
        This method is called AFTER a decision has been made to generate
        a reusable rule for future similar fields.
        
        Args:
            field_info: Dictionary containing field information:
                - question: str
                - field_type: str (radio, checkbox, select, text, number)
                - options: Optional[List[str]]
                - required: bool
            selected_value: The value that was selected for this field
            profile: Candidate profile
            job_context: Optional job context (job title, description, etc.)
            
        Returns:
            RuleSuggestion if rule generation succeeds, None otherwise
        """
        pass

